# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Sub Navigation Summary
  description: Displays a summary image, description and links to sub-pages.
  icon: article
  tags: ["navigation"]

# Defines the structure of this component, as well as the default values
blueprint:
  component_palette: lightest
  full_container_width: false
  navigation_group:
  navigation_group_is_collection: false
  collection_has_categories: false
  content_alignment:
  content_padding_top: 5
  content_padding_bottom: 5

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  navigation_group:
    comment: "Select the group name used in the navigation data file ('_data/nav.json') to label the group of sub-navigation items (e.g. 'Service Fleet'). Will likely match the top-level title for the parent (top-level) navigation item."
  navigation_group_is_collection:
    comment: "Check this box if the pages in the navigation group (that make up the sub-navigation) are part of a collection (e.g. 'service-fleet'). The navigation group name will be processed by making it lowercase and hypenating spaces. This processed name needs to match the collection name."
  collection_has_categories:
    comment: "Check this box if the collection has an associated data file with categories (e.g '_data/service-fleet-categories.json'). The data file filename should be in format of (hyphenated) '(collection name)-categories.json'(e.g. 'service-fleet-categories.json')."