# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Sponsors
  description: Useful to display multiple logos.
  icon: type_specimen
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  sponsors:
    - title: Title
      sponsor_image:
      link:
  grayscale: false
  content_padding_top: 5
  content_padding_bottom: 5

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  sponsor_image:
    type: image
    options:
      width: 400
      height: 400
      resize_style: contain
      expandable: false
      paths:
        uploads: uploads/sponsors
    label: Sponsor Image