# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Gallery
  description: Lightbox gallery (uses Fullscreen Lightbox).
  icon: add_a_photo
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  component_palette: lightest
  photos:
  reverse_photo_order: false
  content_padding_top: 5
  content_padding_bottom: 5

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: