# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Feature Image
  description: Basic single feature image.
  icon: stars
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  feature_image:
  component_palette: lightest
  content_padding_top: 0
  content_padding_bottom: 0

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
