# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Snazzy Map
  description: Custom map (via Google Maps API).
  icon: place
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  snazzy_map_link:
  map_height:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  snazzy_map_link:
    comment: "From snazzymaps.com. Applies styling to Google Map. Requires Google Map API key at snazzymaps.com"
  map_height:
    comment: "In pixels (number only)."