# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: YouTube
  description: Embed videos (uses YouTube API).
  icon: smart_display
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title:
  cover_image:
  video_id:
  constrain_to_container: false
  component_palette: lightest
  content_padding_top: 5
  content_padding_bottom: 5

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  cover_image:
    type: image
    options:
      width: 1400
      height: 1400
      resize_style: contain
      expandable: false
      paths:
        uploads: uploads/youtube
    label: Video Cover Image
  constrain_to_container:
    type: checkbox
    comment: "When checked, constrains the player to being inside of the wrapper div ratehr than full viewport width."
  component_palette:
    hidden: "!constrain_to_container"
  content_padding_top:
    hidden: "!constrain_to_container"
  content_padding_bottom:
    hidden: "!constrain_to_container"