# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Feature
  description: Feature image with text.
  icon: stars
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  component_palette: lightest
  title: Title...
  description: Content...
  img:
    feature_image:
    title:
    crop: "auto"
    use_parallax: false
  button:
    link: /
    text: Link Button
    hide_button: false
  reversed: false
  content_padding_top: 5
  content_padding_bottom: 5

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
  reversed:
    type: checkbox
    comment: "Reverse items from left to right"
  feature_image:
    type: image
    options:
      width: 1200
      height: 1200
      resize_style: contain
      expandable: false
      paths:
        uploads: uploads/feature
    label: Feature Image
  use_parallax:
    type: checkbox 
    comment: "Enables a parallax scrolling effect on the hero image (disabled for mobile - below 1024px)."
  crop:
    type: select
    options:
      allow_empty: false
      values:
        "auto": "Original"
        "1": "Square"
        "1.33": "Wide"
        "0.75": "Tall"
  