# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Team
  description: Multiple team member bio and pic.
  icon: groups
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  pattern:
  crop: "auto"
  team_member:
  content_padding_top: 5
  content_padding_bottom: 5

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  pattern:
    type: select
    label: Layout
    options:
      allow_empty: false
      values:
        "image-left-alternating": "Alternating - First Image Left"
        "image-right-alternating": "Alternating - First Image Right"
        "image-left": "Image Left"
        "image-right": "Image Right"
  crop:
    type: select
    options:
      allow_empty: false
      values:
        "auto": "Original"
        "1": "Square"
        "1.33": "Wide"
        "0.75": "Tall"
    
_structures:
  team_member:
    values:
      - label: Team Member
        text_key: name
        subtext_key: title
        image_key: team_image
        icon: person
        value:
          component_palette: lightest
          name: Name...
          title: Title...
          description: Description...
          team_image:
        _inputs:
          description:
            type: markdown
            label: Description