# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Feature Smooth
  description: Smooth background colour transitions.
  icon: stars
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  pattern:
  crop: "auto"
  feature_item:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  pattern:
    type: select
    label: Layout
    options:
      allow_empty: false
      values:
        "image-left-alternating": "Alternating - First Image Left"
        "image-right-alternating": "Alternating - First Image Right"
        "image-left": "Image Left"
        "image-right": "Image Right"
  crop:
    type: select
    options:
      allow_empty: false
      values:
        "auto": "Original"
        "1": "Square"
        "1.33": "Wide"
        "0.75": "Tall"
    
_structures:
  feature_item:
    values:
      - label: Feature Item
        text_key: title
        subtext_key:
        image_key: image
        icon: person
        value:
          title: Title...
          description: Description...
          feature_image:
          background_color:
          text_color: